site_name: Rivery Command Line Tool (CLI)
repo_url: https://github.com/RiveryIo/rivery_cli
repo_name: RiveryIo/rivery_cli
edit_uri: edit/docs/docs
site_url: https://clidocs.rivery.io
extra_css: 
  - stylesheets/rivery_light.css

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  favicon: assets/Rivery - favicon.png
  logo: assets/Rivery - favicon.png
  custom_dir: docs/theme_overrides
  palette:
    scheme: default

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Reference:
      - Authentication: reference/authentication.md
      - Basics: reference/best-practice.md
      - Project: reference/project.md
      - Models:
        - reference/reference.md
        - River:
          - Yaml Reference: reference/rivers/river.md
          - Properties:
              - Logic: reference/rivers/logic/logic.md
  - Commands:
    - commands/rivery.md
    - init: commands/rivery-init.md
    - configure: commands/rivery-configure.md
    - profiles:
      - commands/profiles/profiles.md
      - profiles get: commands/profiles/profiles-get.md
    - rivers:
        - commands/rivers/rivery-rivers.md
        - rivers import: commands/rivers/rivers-import.md
        - rivers push: commands/rivers/rivers-push.md
        - rivers run:
          - commands/rivers/rivers-run.md
          - rivers run fire: commands/rivers/run-fire.md
          - rivers run status: commands/rivers/run-status.md
    - activities:
        - commands/activities/rivery-activities.md
        - activities logs:
            - commands/activities/activities-logs.md
            - activities logs fetch: commands/activities/logs-fetch.md
  - Resources:
    - Glossary: resources/glossary.md
    - FAQ: resources/faq.md




